version: '3'

x-redis-master-base: &redis-master-base
  image: redis/redis-stack-server:7.4.0-rc2
  networks:
    - redis-cluster
  command: redis-server /usr/local/etc/redis/redis.conf

x-redis-slave-base: &redis-slave-base
  image: redis/redis-stack-server:7.4.0-rc2
  networks:
    - redis-cluster
  depends_on:
    - redis-master
  command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379

x-sentinel-base: &sentinel-base
  image: redis:7.4-rc2
  networks:
    - redis-cluster
  depends_on:
    - redis-master
    - redis-slave-1
    - redis-slave-2
  command: redis-sentinel /usr/local/etc/redis/redis.conf

services:
  redis-master:
    <<: *redis-master-base
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      redis-cluster:
        ipv4_address: 172.21.0.2
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/master:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/master/:/data

  redis-slave-1:
    <<: *redis-slave-base
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    networks:
      redis-cluster:
        ipv4_address: 172.21.0.3
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/slave1:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/slave1:/data
    
  redis-slave-2:
    <<: *redis-slave-base
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    networks:
      redis-cluster:
        ipv4_address: 172.21.0.4
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/slave2:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/slave2/:/data

  sentinel-1:
    <<: *sentinel-base
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/sentinel1:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/sentinel1/:/data

  sentinel-2:
    <<: *sentinel-base
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/sentinel2:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/sentinel2/:/data

  sentinel-3:
    <<: *sentinel-base
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    volumes:
      - /volume2/docker/redis-sentinel-cluster/conf/sentinel3:/usr/local/etc/redis
      - /volume2/docker/redis-sentinel-cluster/data/sentinel3/:/data

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          ip_range: 172.21.0.0/20